name: qa
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Java
        run: ./gradlew ktfmtCheck
      - name: Javascript
        run: |
          cd js
          npm i --only=dev
          npm run check
